# site properties and page defaults
title: Bhatlab
subtitle: We work on various aspects of glioblastma biology
description: Our lab studies focus on the aggressive brain tumor - glioblastoma(GBM). We examine the factors driving immune resistance and how transcription factors and immune cells are reprogrammed in GBM.
header: images/background_mayo.jpg
footer: images/background_mayo.jpg
proofer: false

# site social media and other links
links:
  email: Bhat.Krishna@mayo.edu
  orcid: 0000-0001-6783-1894
  google-scholar: ETJoidYAAAAJ 
  github: bhatlab
  twitter: bhatlab
  youtube: bhatlab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
